spring:
  application:
    name: Balance transactions

  docker:
    compose:
      enabled: true


  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER:localhost:5432/BalanceTransactions}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:jasur1803}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect



application:
  rca:
    private-key: ${PRIVATE_KEY_PATH:classpath:keys/private_key.pem}
    public-key: ${PUBLIC_KEY_PATH:classpath:keys/public_key.pem}

springdoc:
  swagger-ui:
    path:/swagger-ui.html

